--
-- Name: tbl_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_category (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tbl_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbl_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_order (
    id bigint NOT NULL,
    moment timestamp without time zone,
    order_status integer,
    client_id bigint
);


--
-- Name: tbl_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbl_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_order_item (
    price double precision,
    quantity integer,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: tbl_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_payment (
    moment timestamp without time zone,
    order_id bigint NOT NULL
);


--
-- Name: tbl_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_product (
    id bigint NOT NULL,
    description character varying(255),
    img_url character varying(255),
    name character varying(255),
    price double precision
);


--
-- Name: tbl_product_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_product_category (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: tbl_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbl_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbl_user (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255)
);


--
-- Name: tbl_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbl_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_category tbl_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_category
    ADD CONSTRAINT tbl_category_pkey PRIMARY KEY (id);


--
-- Name: tbl_order_item tbl_order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_order_item
    ADD CONSTRAINT tbl_order_item_pkey PRIMARY KEY (order_id, product_id);


--
-- Name: tbl_order tbl_order_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_order
    ADD CONSTRAINT tbl_order_pkey PRIMARY KEY (id);


--
-- Name: tbl_payment tbl_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_payment
    ADD CONSTRAINT tbl_payment_pkey PRIMARY KEY (order_id);


--
-- Name: tbl_product_category tbl_product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_product_category
    ADD CONSTRAINT tbl_product_category_pkey PRIMARY KEY (product_id, category_id);


--
-- Name: tbl_product tbl_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_product
    ADD CONSTRAINT tbl_product_pkey PRIMARY KEY (id);


--
-- Name: tbl_user tbl_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_pkey PRIMARY KEY (id);


--
-- Name: tbl_order_item fk1oy9x003q55eqmuiv0y8a15e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_order_item
    ADD CONSTRAINT fk1oy9x003q55eqmuiv0y8a15e FOREIGN KEY (product_id) REFERENCES public.tbl_product(id);


--
-- Name: tbl_payment fkac54xp3r2r3m9datds9351ric; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_payment
    ADD CONSTRAINT fkac54xp3r2r3m9datds9351ric FOREIGN KEY (order_id) REFERENCES public.tbl_order(id);


--
-- Name: tbl_product_category fkjkbn47tecomukeudhg92tlc15; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_product_category
    ADD CONSTRAINT fkjkbn47tecomukeudhg92tlc15 FOREIGN KEY (category_id) REFERENCES public.tbl_category(id);


--
-- Name: tbl_product_category fklwd56rummt6sunb6fl3t6002r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_product_category
    ADD CONSTRAINT fklwd56rummt6sunb6fl3t6002r FOREIGN KEY (product_id) REFERENCES public.tbl_product(id);


--
-- Name: tbl_order_item fkmkqpajkg6p2wq4owcv1v08pc5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_order_item
    ADD CONSTRAINT fkmkqpajkg6p2wq4owcv1v08pc5 FOREIGN KEY (order_id) REFERENCES public.tbl_order(id);


--
-- Name: tbl_order fknwpd32wrmgyhxrgvnw8dvm7jj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbl_order
    ADD CONSTRAINT fknwpd32wrmgyhxrgvnw8dvm7jj FOREIGN KEY (client_id) REFERENCES public.tbl_user(id);


--
-- PostgreSQL database dump complete
--

